### ISSUE TITLE
Can't Find StoredProcedure

### ISSUE THREAD

**Issue by HigginDazs** [geral2/SQL-APIConsumer#10]
Able to create the CLR Assembly, but receive an error when I try to create the CLR Stored Procedures:

`Could not find Type 'StoredProcedures' in assembly 'APIConsumer'.`

Perhaps I have missed a step or failed to build the Assembly correctly? I found Step 5 in the Readme a little unclear.

**Comment by HigginDazs** [comment]
Apologies, I realised I had built from the wrong dll. Closing now.

**Comment by geral2** [comment]
I tried to clarify Step 5. Thank you!
