### ISSUE TITLE
Authoriziation

### ISSUE THREAD

**Issue by deansterdean** [geral2/SQL-APIConsumer#11]
Thanks for the readme update,  Once I pulled the files into my CLR I was able to create the calls and run the samples.  Now I am making a call to a third party to retrieve Json formatted data. In Postman I send the string with Basic Auth entering my username and password.  The  authorization header is automatically generated on the send to allow the access.
Do you have an API_Consumer proc that uses the auth in a header or
how would I handle constructing a get request requiring basic authentication sent in the header. Where each request requires the username and password in a header.

Thanks for the additional help

**Comment by geral2** [comment]
Hey, I will take a look to it at night, and I'll update the code. I think that actually we just can send credentials in Post method as JsonBody.

Is that a public service that I can test?

**Comment by deansterdean** [comment]
I really do appreciate your quick response and help but Unfortunately this is not something we can use for test  since it is a private service that we have purchased and contains sensitive data.




________________________________

**Comment by geral2** [comment]
Don't worry I will create an API to try to reproduce this scenario. I will let you know tonight.

**Comment by geral2** [comment]
@deansterdean before doing anything could you please try this:

```
 DECLARE @Credentials AS VARCHAR(MAX)
    
    SET @Credentials = CONCAT('Basic ','user:pass')
    
    EXEC [dbo].[APICaller_GETAuth] 
         @URL	  = 'http://localhost:5000/api/values'
       , @Token  = @Credentials
```

**Comment by geral2** [comment]
This was already covered on bug #2. Instead of sending token send the Basic Auth, like this:

```
DECLARE @Credentials AS VARCHAR(MAX)
    
    SET @Credentials = CONCAT('Basic ','user:pass')
    
    EXEC [dbo].[APICaller_GETAuth] 
         @URL	  = 'http://localhost:5000/api/values'
       , @Token  = @Credentials
```
