### ISSUE TITLE
Problem with UTF8

### ISSUE THREAD

**Issue by mostafahk** [geral2/SQL-APIConsumer#12]
It returns ????? when UFT charset is in responce.

In APIConsumer.cs :

modify :
using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
to:
using (var streamReader = new StreamReader(httpResponse.GetResponseStream(),Encoding.UTF8) )

Thnks

**Comment by mostafahk** [comment]
I fixed by adding this too:
JsonConvert.ToString(unicodestring, '"', StringEscapeHandling.EscapeNonAscii);

**Comment by mostafahk** [comment]
I'm sorry to say again 😭 
I used this function in response string and worked very fine.

static string EncodeNonAsciiCharacters(string value)
        {
            StringBuilder sb = new StringBuilder();
            foreach (char c in value)
            {
                if (c > 127)
                {
                    // This character is too big for ASCII
                    string encodedValue = "\\u" + ((int)c).ToString("x4");
                    sb.Append(encodedValue);
                }
                else
                {
                    sb.Append(c);
                }
            }
            return sb.ToString();
        }


return EncodeNonAsciiCharacters(ContentResult);

**Comment by geral2** [comment]
@mostafahk Could you please upload the error that it's throwing?.
