### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by bierfust** [geral2/SQL-APIConsumer#14]
I'm trying to do an api call where an apiKey and a secretKey is required. I'm using APICaller_GETAuth. I get an error: "The remote server returned an error: (401) Unauthorized."

Am I using the APICaller_GETAuth incorrectly? Do you have maybe recommendations how I could change the TSQL code so that the api call will work?

More information about the REST API can be found here:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

Thanks in advance.

**TSQL code**
```
-- Get Timestap
 Declare @ts as table(Json_Table nvarchar(max))

 INSERT into @ts (Json_Table) 
 exec [dbo].[APICaller_GET]@URL = 'https://api.binance.com/api/v1/time'

-- Set Variables
Declare @timestamp varchar(max) =	(SELECT * 
								FROM OPENJSON((select * from @ts))
								WITH (   
								[servertime] varchar(max) '$.serverTime'      
								))
Declare @apiKey varchar(max) = 'USERAPIKEY'
Declare @secretKey varchar(max) = 'USERSECRETKEY'
Declare @header varchar(max) = concat('X-MBX-APIKEY = ', @apiKey)
Declare @wurl varchar(max) = concat('https://api.binance.com/api/v3/account?timestamp=',@timestamp, '&signature=', @secretKey)

 --Get Account Data
 exec [dbo].[APICaller_GETAuth] @token = @header,
							@URL = @wurl 
```

**Comment by geral2** [comment]
Hello there,

I'm working in an update that would allow you call an API and send multiple customize Header for instance X-MBX-APIKEY, and Authorization. It will also show the correct error returned by the Server.

Tomorrow I will upload it. But in advance those are error for the API. I have a Binance account, I did configured the API managment, when I was trying to call the accout end point it was throwing this errors below:
-1021 INVALID_TIMESTAMP
{
    "code": -1021,
    "msg": "Timestamp for this request is outside of the recvWindow."
}

However I will keep trying, tomorrow I will let you know.

**Comment by bierfust** [comment]
I found this for error -1021:

1. https://github.com/sammchardy/python-binance/issues/238

**Solution 1**
My system's time was out of sync with Binance's, despite it being automatically set. Changed the time server and my problem was solved.

Or maybe you can set a fixed value for the recvWindow.

```
Declare @apiKey varchar(max) = 'USERAPIKEY'
Declare @secretKey varchar(max) = 'USERSECRETKEY'
Declare @timestamp varchar(max) = '1565418598807'
Declare @recvWindow varchar(max) = '5000'
Declare @header varchar(max) = concat('X-MBX-APIKEY = ', @apiKey)
Declare @wurl varchar(max) = concat('https://api.binance.com/api/v3/account?timestamp=',@timestamp, '&recvWindow=', @recvWindow , '&signature=', @secretKey)

 --Get Account Data
 exec [dbo].[APICaller_GETAuth] @token = @header,
							@URL = @wurl 
```

**You get this URL**
https://api.binance.com/api/v3/account?timestamp=1565418598807&recvWindow=5000&signature=USERSECRETKEY

**Comment by geral2** [comment]
Hey bro, I just updated the repo in which I show the correct servers errror. I also added some utilities methods that could help calling the Binance API.

select [dbo].[GetTimestamp]()
 --Set TimeStamp parameter
select @timeStamp = CONCAT(@timeStamp, [dbo].[GetTimestamp]())

--Set Signature parameter
SELECT @Signature = [dbo].[Create_HMACSHA256](@timeStamp,@secretKey)

I tested with my account, and it worked as perfectly. 

Keep in mind that you need to pass an HMACSHA256 as signature not the secret key plane.

Below the script that I used... Any issue please let me know.

use TESTER
go 
--Test Binance API method:time
exec [dbo].[APICaller_GET] @URL = 'https://api.binance.com/api/v1/time'

--Declare Variables
DECLARE  @timeStamp AS VARCHAR(50) = 'timestamp='
		,@Signature AS VARCHAR(200) 
		,@secretKey varchar(max) = '**YourSecretKey**'

--Set TimeStamp parameter
select @timeStamp = CONCAT(@timeStamp, [dbo].[GetTimestamp]())

--Set Signature parameter
SELECT @Signature = [dbo].[Create_HMACSHA256](@timeStamp,@secretKey)

--SELECT @Signature ,@timeStamp

--Set Header
Declare @header nvarchar(max) = '[{
								  "Name": "X-MBX-APIKEY",
								  "Value" :"**YourAPIKEY**"
								}]';
--Set URL
Declare @wurl varchar(max) = concat('https://api.binance.com/api/v3/account?',@timeStamp, '&signature=', @Signature)

Declare @ts as table(Json_Table nvarchar(max))

 insert into @ts
 --Get Account Data
 exec [dbo].APICaller_GET_headers
							@wurl
							,@header

SELECT  * 
 FROM OPENJSON((select * from @ts))  
		WITH (   
				 "makerCommission"	nvarchar(max) '$."makerCommission"'      
				,"takerCommission"	nvarchar(max) '$."takerCommission"'      
				,"buyerCommission"	nvarchar(max) '$."buyerCommission"'      
				,"sellerCommission" nvarchar(max) '$."sellerCommission"'      
				,"canTrade"			nvarchar(max) '$."canTrade"'      
				,"canWithdraw"		nvarchar(max) '$."canWithdraw"'      
				,"canDeposit"		nvarchar(max) '$."canDeposit"'      
				,"updateTime"		nvarchar(max) '$."updateTime"'      
				,"accountType"		nvarchar(max) '$."accountType"'      
				,"balances"			nvarchar(max)  '$.balances'  as JSON   
				) a
	OUTER APPLY OPENJSON(a.balances)
	WITH
        (
             asset			NVARCHAR(50)
            ,"free"			NVARCHAR(50)  
			,"locked"		NVARCHAR(50)  
        ) AS b
