### ISSUE TITLE
Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by ram140281** [geral2/SQL-APIConsumer#15]
Hello,

When I am trying to connect secure URL and getting an error "Could not create SSL/TLS secure channel."

I am using SQL Server 2017.

```sql
  exec  [dbo].[APICaller_POST]
    	 @URL = 'https://{SOME_SECURE_URL}'
    	,@JsonBody = '{"Password":"*****"}'
```

**Comment by ram140281** [comment]
Any suggestion Bro!

**Comment by geral2** [comment]
Sorry for the late response. Yes, saw a property that could be added to the web method I will modify it and let you know tonight.

```
ServicePointManager.Expect100Continue = true;
        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls
               | SecurityProtocolType.Tls11
               | SecurityProtocolType.Tls12
               | SecurityProtocolType.Ssl3;
```

**Comment by geral2** [comment]
Hey bro, I just uploaded a new version adding the code above. Could you please give a try and let met know.

**Comment by ram140281** [comment]
Hi Geral,

I tried using new code but now I getting error "Object reference not set to an instance of an object."

exec  [dbo].[APICaller_POST]
    	 @URL = 'https://{SOME_SECURE_URL}'
    	,@JsonBody = '{"password":"*****"}'

**Comment by geral2** [comment]
Hey @ram140281  could you please give a try again.

I just fixed it. I tested using the code below. in a local web service.

EXEC [dbo].[APICaller_POST]
	@URL = 'https://localhost:44390/api/libros'
	,	@JsonBody = '{
						"Titulo" : "El principito",
						"AutorId": 2
					 }'

exec [APICaller_GET]	@URL = 'https://localhost:44390/api/libros'

**Comment by ram140281** [comment]
Nothing fixed. I am not going to follow it anymore.
Thanks

**Comment by geral2** [comment]
Did you re-deploy the new changes properly?. Did your API worked through PostMan?.

It was throwing same error before I deployed the new changes.
