### ISSUE TITLE
APICaller_GETAuth returns max of 65,535 chars

### ISSUE THREAD

**Issue by valentinb1** [geral2/SQL-APIConsumer#19]
I am running into issue where APICaller_GETAuth is cutting-off the Json string at 65535. Perhaps there is a "ushort" counter somewhere that is creating this issue. Would you please look into this. I was attempting to debug but the project would not compile because of the "Importing key file was canceled" issue.

The test SQL I used is:
Declare @ts as table(Json_Table nvarchar(max))
INSERT INTO @ts EXEC [dbo].APICaller_GETAuth 
    @URL ='https://www.xxx.com/ibis/rest/api/v2/locations'
   , @Token = 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJjb2................'
SELECT  * 
 FROM OPENJSON((select * from @ts), '$.data.locations')  
		WITH	( 					
					imei nvarchar(max)					
				) a   
The Bearer key is invalid in this example, but if you need the key to test I can email it to you.
Thank you for the great work on this project. It looks very promising.

**Comment by geral2** [comment]
Hello,

I will take a look in 3 hour when I get home. I'll let you know.

Thanks,

**Comment by geral2** [comment]
Hey @valentinb1 , I'm trying to reproduce the issue, Could you please email me the bearer key to geraldo.diaz@hotmail.com?

**Comment by valentinb1** [comment]
Hi Geraldo. I tried to email you but was rejected with: VI1EUR04FT057.mail.protection.outlook.com gave this error:
Requested action not taken: mailbox unavailable.
Here is the Token: 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJjb21wYW55SWQiOiIyODEyNzYiLCJpc3MiOiJhZ2lsaXMiLCJwZXJzb25JZCI6Ijk0OTU5MiIsImV4cCI6MTcyNzEyMjY5NiwiaWF0IjoxNTY5MjY5ODk2LCJ1c2VybmFtZSI6InZhbGVudGluLmJvaWFkamlldkBwYWNpZmljYXRydWNrcy5jb20ifQ.-YNAuh60i_65TzXEv7hGtCHwBmG3oFwQIBypOeD4qdg'
Please let me know when you copy it, so I can delete it from here.
Thank you very much for your help!

**Comment by geral2** [comment]
Done

**Comment by valentinb1** [comment]
Yes, it would be even better. Because I need the data in a table anyway. Thank you Geraldo.

**Comment by valentinb1** [comment]
Geraldo: This was an error on my part. All is working fine. I arrived to the wrong conclusion because I was looking for the resulting Json in Management Studio. Well, the grid of the studio has a limit per cell of  65535 chars. I assumed that this was a bug in your code. I apologize for the mistake. Let's delete this issue, because it is not an issue.

**Comment by geral2** [comment]
Oh!, you are right. I was not aware of that issue. Please do not delete the issue in order to keep this documented. I tested with a temporal table it's behave different that with variables tables.

Would you mind giving a Star to this repo :).

I working on uploading a branch that would return location data as result set.

```
CREATE TABLE #RESULT 
(
 result nvarchar(max)
)

INSERT INTO #RESULT 
exec [APICaller_GETAuth]
@url = 'https://www.commandgps.com/ibis/rest/api/v2/locations'
, @Authorization = 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJjb21wYW55SWQiOiIyODEyNzYiLCJpc3MiOiJhZ2lsaXMiLCJwZXJzb25JZCI6Ijk0OTU5MiIsImV4cCI6MTcyNzEyMjY5NiwiaWF0IjoxNTY5MjY5ODk2LCJ1c2VybmFtZSI6InZhbGVudGluLmJvaWFkamlldkBwYWNpZmljYXRydWNrcy5jb20ifQ.-YNAuh60i_65TzXEv7hGtCHwBmG3oFwQIBypOeD4qdg'

SELECT *
FROM OPENJSON(
				(
					SELECT *
					FROM #RESULT
				), 
					'$.data.locations') 
			WITH(
					imei NVARCHAR(MAX) 
					,"battery" NVARCHAR(MAX) 
				) a;
```

**Comment by valentinb1** [comment]
Geraldo: Thank you for your superb  work. You created a great tool!
