### ISSUE TITLE
The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by ahmedarafaa** [geral2/SQL-APIConsumer#20]
Hello :),
I use APIConsumer since 1/1/2020 
from 5/2/2020 I get this error 

> The underlying connection was closed: An unexpected error occurred on a send.

I use sql 2014
```
exec  [dbo].[APICaller_POST]
    	@URL = @URLPath
    	,@JsonBody = @Query
```

I tried the API from the postman it's working fine

**Comment by geral2** [comment]
Hey, that's weird I haven't updated any code since October 16th 2019.  
What version of .net framework  are you using?
Is you URL HTTPS or HTTP?

**Comment by ahmedarafaa** [comment]
thanks for your replay 
I'm using .net framework 4.0.30319 and using https

**Comment by lwal73** [comment]
I have been using APIConsumer for a long time.
I had an error at the same time (05/02/2020).
Request was aborted: Failed to create SSL / TLS secure channel.
request example:
exec dbo.APICaller_POST 
	@Url='https://api.telegram.org/bot5xxxxxxxxxxxxxxxxxxxxxx/sendMessage'
	,@JsonBody='{"chat_id":"592xxxx","text":"test"}'
 
Help.

**Comment by geral2** [comment]
Hello,

I wasn't able to reproduce this issue. Let me give a try using Telegram API.

**Comment by lwal73** [comment]
Microsoft SQL Server 2016 (RTM-GDR) (KB4019088) - 13.0.1742.0 (X64)   Jul  5 2017 23:41:17   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 6.3 <X64> (Build 14393: ) 
What information do you provide for a simpler solution path for you ??
Until 05/02/2020 everything worked fine.

**Comment by lwal73** [comment]
I'm from Ukraine

**Comment by geral2** [comment]
Just as a random test, Could you please try calling RoutinNumbers api below:

```
-- How to consume GET API -- How to show Json results.

DECLARE @RoutingNumber AS VARCHAR(50) = '122242597'

--Public API: routingnumbers.info
DECLARE @Url  VARCHAR(200) = CONCAT('https://www.routingnumbers.info/api/name.json?','rn=',@RoutingNumber) 

DECLARE @Results AS TABLE
(
	Context varchar(max)
)

DECLARE @Result AS VARCHAR(MAX)

--INSERT INTO @Results
EXEC  [dbo].[APICaller_GET] @Url
```

**Comment by lwal73** [comment]
the request does not work only with telegrams
With checked on other services, everything works out well.
and there are no telegrams (((
I can check on your request.
just could you please drop the request text, not the picture.

**Comment by lwal73** [comment]
DECLARE @Object AS INT; 
 DECLARE @ResponseText AS VARCHAR(8000); 
 DECLARE @Body AS VARCHAR(8000) =  '{"chat_id":"592xxxxxxxx","text":"привет"}'   
 
 
 EXEC sp_OACreate 'MSXML2.XMLHTTP', @Object OUT; 
 EXEC sp_OAMethod @Object, 'open', NULL, 'post','https://api.telegram.org/bot5xxxxxxxxxxxxxxxxxxxx/sendMessage', 'false' 
 
 
 EXEC sp_OAMethod @Object, 'setRequestHeader', null, 'Content-Type', 'application/json' 
 EXEC sp_OAMethod @Object, 'send', null, @body 
 
 
 EXEC sp_OAMethod @Object, 'responseText', @ResponseText OUTPUT 
 SELECT @ResponseText 
 
EXEC sp_OADestroy @Object 
That's how it works, but for me it’s not very convenient.

**Comment by lwal73** [comment]
не могли бы вы написать мне письмо на еьфшд  lwal@и.ua, я вам отправлю полные данные , что-бы вы могли сами проверить и увидеть ошибки.

**Comment by lwal73** [comment]
The answer to your request worked perfectly.
{"message": "OK", "rn": "122242597", "code": 200, "name": "FIRST CITIZENS BANK"}

**Comment by lwal73** [comment]
Could you write me a letter at lwal@i.ua, I will send you complete data so that you can check and see the errors yourself.

**Comment by geral2** [comment]
Sure!, thank you!

**Comment by lwal73** [comment]
Thank you, I will wait for a test letter from you.

**Comment by geral2** [comment]
Hey @lwal73 @ahmedarafaa  Could you give a try with this version that I just loaded (2.0.0.4)?

**Comment by lwal73** [comment]
Thank you very much. You just saved me.

Thank you, thank you, thank you.

**Comment by ahmedarafaa** [comment]
Hello @geral2 
I try to configure this version 2.0.0.4 with fresh database fresh configuration and i get this error in this step

![image](https://user-images.githubusercontent.com/36604815/74525373-a04ee580-4f29-11ea-9503-e578d572b4fb.png)

`CREATE ASSEMBLY [API_Consumer]
AUTHORIZATION dbo
FROM  N'C:\CLR\APIConsumer.dll'
WITH PERMISSION_SET = UNSAFE`

> Warning: The Microsoft .NET Framework assembly 'system.net.http, version=4.0.1.0, culture=neutral, publickeytoken=b03f5f7f11d50a3a.' you are registering is not fully tested in the SQL Server hosted environment and is not supported. In the future, if you upgrade or service this assembly or the .NET Framework, your CLR integration routine may stop working. Please refer SQL Server Books Online for more details.
Msg 6586, Level 16, State 1, Line 1
Assembly 'System.Net.Http' could not be installed because existing policy would keep it from being used.

**Comment by lwal73** [comment]
Take this dll

 

CREATE ASSEMBLY [API_Consumer]

AUTHORIZATION dbo

FROM  N'C:\CRL\API_Consumer.dll'

WITH PERMISSION_SET = UNSAFE

**Comment by ahmedarafaa** [comment]
@lwal73 
In the new version, the dll name changed from "API_Consumer" to "APIConsumer"

from where you get this part are you compile it by your self or what? more explanation, please 
`FROM  N'C:\CRL\API_Consumer.dll'`

**Comment by geral2** [comment]
@lwal73  you're welcome. Would you mind starting the project?.

@ahmedarafaa Is you check the last commit uploaded, I did not rename that dll.
You could rebuild the project in your environment in order to get a new API_Consumer generated, or you can use the version in the release script [API_Consumer_2.0.0.4](https://github.com/geral2/SQL-APIConsumer/releases/download/2.1.1/API_Consumer_2.0.0.4.sql).

**Comment by lwal73** [comment]
what should I do ?

**Comment by geral2** [comment]
Just click here 

![image](https://user-images.githubusercontent.com/5836150/74541598-47c31c80-4f18-11ea-97b1-edff46d8f22a.png)

**Comment by geral2** [comment]
Btw, this issue was caused due TLS < 1.2 would be deprecated on March 2020. All servers will have to serve their contents using TLS 1.2 at least in order to keep compatibility with the main browsers.

So, since we are using 4.0 Framework, the changed was adding the code below:
```
 ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls
                                                 | SecurityProtocolType.Ssl3 
                                                 | (SecurityProtocolType)3072;
```

This specific part **(SecurityProtocolType)3072;**. Which correspond to SecurityProtocolType.Tls12

**Comment by ahmedarafaa** [comment]
Works for me :D
Thanks @geral2

**Comment by ahmedarafaa** [comment]
the last thing please could you please add "Go" below this line of code

```
PRINT N'Creating [dbo].[APICaller_GET_Headers_BODY]...';
GO --Please add Go in this line
```
