### ISSUE TITLE
APICaller_POSTAuth issue

### ISSUE THREAD

**Issue by johncagnina** [geral2/SQL-APIConsumer#21]
I'm running this in SQL and getting the following error. Can you help?

John

USE [DATABASE]
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[APICaller_POSTAuth]
		@URL = N'https://ssecureurl',
		@Token = N'tokenxxx',
		@JsonBody = N'{"content"}'

SELECT	'Return Value' = @return_value

Error
Object reference not set to an instance of an object.

**Comment by geral2** [comment]
Hey John,

Did you try any other End Point in that URL?... Could you try testing that URL using Postman in order to discard that it's an issue with "https;//ssecureurl"?

**Comment by johncagnina** [comment]
The functional url I'm using does work in Postman

**Comment by geral2** [comment]
Could you please try to execute the code below in order to confirm if it's returning success?

```
exec [dbo].[APICaller_POSTAuth]
@URL = 'https://en51umghbvcwl.x.pipedream.net/' 
,@Token = 'Bearer Token'
,@JsonBody	='{"name":"Test"}'
```

**Comment by johncagnina** [comment]
Interesting... That seem to work. Here is a sample of my code

![3-27-2020 11-28-02 PM](https://user-images.githubusercontent.com/26575726/77813912-d16f1980-7082-11ea-8270-d2786e210642.png)

**Comment by geral2** [comment]
That doesn't look like a Authentication token, it's more like header correct?. In that case try calling the procedure below: 

```
EXEC [dbo].[APICaller_POST_Headers]
	@URL		= 'https://appcenter.ms/api/v0.1/apps/x/push/notifications/'
  , @Headers	=  '[{
					"Name": "X-API-TOken",
					"Value" :"x"
					 }]' 
  , @jSON		= '{body}'
GO
```

In case it doesn't exists:
```

CREATE PROCEDURE [dbo].[APICaller_POST_Headers]
	@URL NVARCHAR (MAX)  
  , @Headers NVARCHAR (MAX)  
  , @jSON NVARCHAR (MAX)  
AS EXTERNAL NAME [API_Consumer].[StoredProcedures].APICaller_POST_JsonBody_Headers

```

**Comment by johncagnina** [comment]
@geral2 that was it! Thank you very much. Great product!

**Comment by geral2** [comment]
Could you please star the Project?

**Comment by johncagnina** [comment]
Done and thanks again!

**Comment by iamoop** [comment]
Just wanted you to know that this answer helped me tremendously as well. And this is truly a great product and I am very thankful that I found it.

**Comment by geral2** [comment]
Great to read that!.
