### ISSUE TITLE
issue with APICaller_GET_Json

### ISSUE THREAD

**Issue by greenlightman** [geral2/SQL-APIConsumer#22]
Hello Geraldo. I'm getting the following error when going through the assembly installation steps for API_Consumer. The first one is below. Any ideas? Muchisimas gracias desde Tampa!

`PRINT N'Creating [dbo].[Create_HMACSHA256]...';
GO
CREATE FUNCTION [dbo].[Create_HMACSHA256]
(@message NVARCHAR (MAX) NULL, @SecretKey NVARCHAR (MAX) NULL)
RETURNS NVARCHAR (MAX)
AS
 EXTERNAL NAME [API_Consumer].[UserDefinedFunctions].[Create_HMACSHA256]`

Creating [dbo].[Create_HMACSHA256]...
Msg 6505, Level 16, State 2, Procedure Create_HMACSHA256, Line 1 [Batch Start Line 3]
Could not find Type 'UserDefinedFunctions' in assembly 'API_Consumer'.

Completion time: 2020-04-09T02:45:34.3158410-04:00

**Comment by geral2** [comment]
Saludos @greenlightman!,

Could you pease confirm the API Consumer version you have instaled?

![image](https://user-images.githubusercontent.com/5836150/78912951-431d6f00-7a56-11ea-8612-efe4865d69ce.png)

**Comment by greenlightman** [comment]
unfortunately, i don't have VS to read the dll. i did download it from SQL-APIConsumer/API_Consumer/obj/Debug/

![Capture](https://user-images.githubusercontent.com/63386680/78915799-795ced80-7a5a-11ea-8187-22fe92c2a0cc.PNG)

**Comment by geral2** [comment]
I meant in MSSM;

![image](https://user-images.githubusercontent.com/5836150/78925219-1a52a500-7a69-11ea-8e4d-8fac1c17eb00.png)

Could you please try running the script in the last release [API_Consumer_2.0.0.4.sql](https://github.com/geral2/SQL-APIConsumer/releases/download/2.1.1/API_Consumer_2.0.0.4.sql). It can be done with ALTER instead of create, in order to confirm you have 2.0.0.4 version in which is this new function [Create_HMACSHA256].

In other hand, if you doesn't require using this function, you could skip creating it.

**Comment by greenlightman** [comment]
i tried it but i'm stuck, see below.
![Capture](https://user-images.githubusercontent.com/63386680/78927195-74089e80-7a6c-11ea-9b5b-02f605981fab.PNG)

**Comment by greenlightman** [comment]
then i tried to drop the assembly, but then got this
![Capture](https://user-images.githubusercontent.com/63386680/78927256-91d60380-7a6c-11ea-9735-6a41bc8580d6.PNG)

**Comment by geral2** [comment]
Gotcha!, you need to drop all the Stored procedures and functions created that rely on API_Consumer assembly. Then try again.

**Comment by greenlightman** [comment]
ño! ok, i missed that. thanks! pls keep this open, i'm starting from the top, i might stumble again!

**Comment by geral2** [comment]
It's ok! :). Could you please star the project?

**Comment by greenlightman** [comment]
done, but pls keep it open! my brain is fried + might need help along the way! gracias papa!

**Comment by greenlightman** [comment]
saludos geraldo! al fin pude completar tu proyecto... gracias. sin embargo, estoy tratando de adaptar APICaller_POST para obtener un token a de un graphQL API. tu metodo deberia funcionar con graphQL, verdad? estoy utilizando 2 valores: clientid con un valor secreto. adjunto es una imagen del POST que funciona con Postman. gracias geraldo!
![Capture](https://user-images.githubusercontent.com/63386680/79036666-7f58e880-7b98-11ea-8d1f-7a4ac118b3ff.PNG)

**Comment by geral2** [comment]
Saludos,

Que parametro require ese EndPoint?. Algun Token y header?. Que procedure ejecutaste para esta llamada?

**Comment by greenlightman** [comment]
Buenos dias Geraldo. Estos son los headers que se usan para el POST. El resultado the devuelve un token. Estoy tratando de adaptar [APICaller_POST] pero estoy atorado! Muchas gracias Geraldo!

endpoint = https://api.qqqtest.com
content-type = application/x-www-form-urlencoded
host = qqqtest.auth0.com
grant_type = client_credentials
client_ID = xxxxxx
client_pwd = yyyyy
audience = https://api.qqqtest.com

**Comment by geral2** [comment]
Intenta con esto:

```
go 
--Set Header
Declare @header nvarchar(max) = '[{
								  "Name": "content-type",
								  "Value" :"application/x-www-form-urlencoded"
								},{
								  "Name": "host",
								  "Value" :"qqqtest.auth0.com"
								},{
								  "Name": "grant_type",
								  "Value" :"client_credentials"
								},{
								  "Name": "client_ID",
								  "Value" :"xxxxxx"
								}
								,{
								  "Name": "client_pwd",
								  "Value" :"yyyyy"
								},{
								  "Name": "audience",
								  "Value" :"https://api.qqqtest.com"
								}]';
--Set URL
Declare @wurl varchar(max) = 'https://api.qqqtest.com'

 exec [dbo].APICaller_POST_Headers
							@wurl
							,@header 

```

**Comment by greenlightman** [comment]
perdona, me equivoque!

el unico header es 'content-type = application/x-www-form-urlencoded'

el resto de los parametros tienen que pasar como 'body' concatenados. Gracias Geraldo!

**Comment by geral2** [comment]
Tienes la estructura de ese Json?

**Comment by greenlightman** [comment]
en Postman, esto es lo que devuelve el API. gracias Geraldo.

![Capture](https://user-images.githubusercontent.com/63386680/79154643-e5628d00-7d9d-11ea-92c5-8adad15c6152.PNG)

**Comment by geral2** [comment]
Me referia al JsonBody que mandas en el request.

Pero intenta con este Stored procedure, si no existe crealo:

```
go
CREATE PROCEDURE [dbo].[APICaller_POST_Headers]
	@URL NVARCHAR (MAX)  
  , @Headers NVARCHAR (MAX)  
  , @jSON NVARCHAR (MAX)  
AS EXTERNAL NAME [API_Consumer].[StoredProcedures].APICaller_POST_JsonBody_Headers

go 
```
```
--Set Header
Declare @header nvarchar(max) = '[{
								  "Name": "content-type",
								  "Value" :"application/x-www-form-urlencoded"
								}]';

Declare @jsonBody nvarchar(max) = '{
								   "host" : "qqqtest.auth0.com",
								   "grant_type" : "client_credentials",
								   "client_ID" : "xxxxxx",
								   "client_pwd" : "yyyyy",
								   "audience" : "https://api.qqqtest.com" 
								 } '
--Set URL
Declare @wurl varchar(max) = 'https://api.qqqtest.com'

 exec [dbo].APICaller_POST_Headers
							@wurl
							,@header 
							,@jsonBody
```

Let me know.

**Comment by greenlightman** [comment]
voy a tratar lo que me sugieres. mientras tanto, aqui es el JSON. gracias Geraldo!

`var settings = {
  "url": "https://qqqtest.auth0.com/oauth/token",
  "method": "POST",
  "timeout": 0,
  "headers": {
    "Content-Type": ["application/x-www-form-urlencoded", "application/x-www-form-urlencoded"],
    "Cookie": "did=s%3Av0%3A18f13590-749d-11eacJ8syY"
  },
  "data": {
    "grant_type": "client_credentials",
    "client_id": "xxxxx",
    "client_pwd": "yyyyy",
    "audience": "https://api.qqqtest.com"
  }
};

$.ajax(settings).done(function (response) {
  console.log(response);
});`

**Comment by geral2** [comment]
Did it work?

**Comment by greenlightman** [comment]
No. todavia. he tratado de ajustar el JSON que sale del POST pero ahora me sale con el error de abajo. pase por algo semejante con pruebas de conexion en Postman, pero al fin logre con los parametros que te indique.

Creo que hay que ajustar algo en [API_Consumer].[StoredProcedures].[APICaller_POST] pero no lo he encontrado todavia. algunas ideas? muchas gracias Geraldo.

`Result
{"error":"access_denied","error_description":"Unauthorized"}`

**Comment by geral2** [comment]
Si retorna eso quiere decir que ya se comunica con el API pero algo en el Json o header no es valido. Veo que arriba tiene un dato adicional en el JsonBody (Host). 

Trata mandando el body dentro de data. Y removiendo el host.

Que cambiaste en Postman btw?
```
--Set Header
Declare @header nvarchar(max) = '[{
								  "Name": "content-type",
								  "Value" :"application/x-www-form-urlencoded"
								}]';

Declare @jsonBody nvarchar(max) = '"data" : {
								   "host" : "qqqtest.auth0.com",
								   "grant_type" : "client_credentials",
								   "client_ID" : "xxxxxx",
								   "client_pwd" : "yyyyy",
								   "audience" : "https://api.qqqtest.com" 
								 } '
--Set URL
Declare @wurl varchar(max) = 'https://api.qqqtest.com'

 exec [dbo].APICaller_POST_Headers
							@wurl
							,@header 
							,@jsonBody
```

**Comment by greenlightman** [comment]
creo que no cambie nada en Postman. definitivament este JSON funciona.

`var settings = {
  "url": "https://qqqtest.auth0.com/oauth/token",
  "method": "POST",
  "timeout": 0,
  "headers": {
    "Content-Type": ["application/x-www-form-urlencoded", "application/x-www-form-urlencoded"],
    "Cookie": "did=s%CJkjeR243P0GScJ8syY"
  },
  "data": {
    "grant_type": "client_credentials",
    "client_id": "xxxx",
    "client_secret": "yyyy",
    "audience": "https://qqqtest.rtafleet.com"
  }
};

$.ajax(settings).done(function (response) {
  console.log(response);
});`

**Comment by greenlightman** [comment]
trate el ajuste anterior que me sugeriste y me devolvio esto

`Error
The 'content-type' header must be modified using the appropriate property or method.  Parameter name: name`

Entonces cambie el @header a esto

`--Set Header
Declare @header nvarchar(max) = '[{
								  "content-type" :"application/x-www-form-urlencoded"
								}]';`

y me devuelve esto

`Result
invalid json`

**Comment by greenlightman** [comment]
trate el ajuste anterior que me sugeriste y me devolvio esto

`Error
The 'content-type' header must be modified using the appropriate property or method.  Parameter name: name`

Entonces cambie el @header a esto

`--Set Header
Declare @header nvarchar(max) = '[{
								  "content-type" :"application/x-www-form-urlencoded"
								}]';`

y me devuelve esto

`Result
invalid json`

**Comment by geral2** [comment]
I think I figured it out. Si, estas usando oauth0.com prueba con esto:

--Set Header
Declare @header nvarchar(max) = '[]';

Declare @jsonBody nvarchar(max) = '"data" : {
								   "grant_type" : "client_credentials",
								   "client_id" : "xxxxxx",
								   "client_secret" : "yyyyy",
								   "audience" : "https://api.qqqtest.com" 
								 } '
--Set URL
Declare @wurl varchar(max) = 'https://api.qqqtest.com'

 exec [dbo].APICaller_POST_Headers
							@wurl
							,@header 
							,@jsonBody

**Comment by greenlightman** [comment]
perdona, no estoy seguro sobre Declare @Header nvarchar(max) = '[]';

mi ultimo intento es

`use QQQTEST_API
go

--Set Header
Declare @header nvarchar(max) = '[{
								  "content-type" :"application/x-www-form-urlencoded"
								  }]';

Declare @jsonBody nvarchar(max) = '{
										   "host" : "qqqtest.auth0.com",
										   "grant_type" : "client_credentials",
										   "client_ID" : "xxxxx",
										   "client_secret" : "yyyyyy",
										   "audience" : "https://api.qqqtest.com" 
										}'

--Set URL
Declare @wurl varchar(max) = 'https://qqqtest.auth0.com/oauth/token'

 exec [dbo].APICaller_POST_Headers
							@wurl
							,@header 
							,@jsonBody`

pero me sale

`Result
{"error":"access_denied","error_description":"Unauthorized"}`

**Comment by geral2** [comment]
Yo probe con esto:

![image](https://user-images.githubusercontent.com/5836150/79274209-3a6fd300-7e72-11ea-9600-4699ae70de8f.png)


```
Declare @header nvarchar(max) = '[]';

Declare @jsonBody nvarchar(max) = '{
								   "grant_type" : "client_credentials",
								   "client_id" : "n4nZKALv06afjo13VSC9ClcAnWdyyoOD",
								   "client_secret" : "vfd7KZv1AWurtZgAkeQvTNoGLoOR_Mx_MCTHbchYVMTuYACgVp03jXqS_tw1cHgM",
								   "audience" : "https://dev-gdiaz.auth0.com/api/v2/" 
								 }'
--Set URL

 
Declare @wurl varchar(max) = 'https://dev-gdiaz.auth0.com/oauth/token'

 exec [dbo].APICaller_POST_Headers
							@wurl
							,@header 
							,@jsonBody
```

**Comment by greenlightman** [comment]
esto esta raro. tu simulacion es identico a lo que pasa exitosamente en Postman, pero no con este codigo. me cerciore que el [client_id] y [client_secret] estan correctos pero me sigue devolviendo esto

`Result
{"error":"access_denied","error_description":"Unauthorized"}`

por lo menos el POST esta mandando lo que espera, pero el resultado me confunde. estas disponible mañana para una consulta? creo que estamos al borde de resolver esto. muchas gracias Geraldo!

**Comment by greenlightman** [comment]
![Capture](https://user-images.githubusercontent.com/63386680/79275471-3d6bc300-7e74-11ea-9aeb-98fbcd34df0e.JPG)

**Comment by geral2** [comment]
Claro, podemos coordinar por AnyDesk o cualquier herramienta.

Creo que el problema esta en tu audience value.

Incluso esto funciona:
```

Declare @header nvarchar(max) = '[]';

Declare @jsonBody nvarchar(max) = '{
								   "grant_type" : "client_credentials",
								   "client_id" : "n4nZKALv06afjo13VSC9ClcAnWdyyoOD",
								   "client_secret" : "vfd7KZv1AWurtZgAkeQvTNoGLoOR_Mx_MCTHbchYVMTuYACgVp03jXqS_tw1cHgM",
								   "audience" : "https://dev-gdiaz.auth0.com/api/v2/" 
								 }'
--Set URL

 
Declare @wurl varchar(max) = 'https://000fleet.auth0.com/oauth/token' 

 exec [dbo].APICaller_POST_Headers
							@wurl
							,@header 
							,@jsonBody

 
```

Intenta algo como esto:   "audience" : "https://000fleet.auth0.com/api/v2/"

**Comment by greenlightman** [comment]
no, estoy seguro que estoy usando la entrada de [audience] correcta. que tal si me comunico mañana contigo? si cualquier plataforma de apoyo que prefieres. gracias de nuevo Geraldo!

![Capture](https://user-images.githubusercontent.com/63386680/79276835-b23ffc80-7e76-11ea-9616-37207e498d3a.PNG)

**Comment by greenlightman** [comment]
saludos Geraldo. todavia no he podido resolver el POST. si estas disponible, que agredeceria si te comunicas conmigo. mi skype es nueve-siete-tres  / nueve-nueve-seis / ocho-seis-dos-uno. tambien me puedes txtear al mismo numero. muchas gracias Geraldo.
