### ISSUE TITLE
For the Example for Calling Authentication and Multiple headers

### ISSUE THREAD

**Issue by iamoop** [geral2/SQL-APIConsumer#24]
I've run into an issue with this part of the example code:
`    SELECT TOP 1 @Token = CONCAT('Bearer ',Json.Token)
     FROM @Result
      CROSS APPLY ( SELECT value AS Token FROM OPENJSON(Result)) AS [Json]`

It's returning an error of Invalid column name 'Result"
Should I be putting something else there? If so? What? The other 

And in the Sample for Multiple Headers when I run it as is I get the error 
Msg 13609, Level 16, State 4, Line 21
JSON text is not properly formatted. Unexpected character 'C' is found at position 0.

I'm very new to the whole JSON stuff, so forgive me if I'm missing something I should know.

Thank you in advance.

**Comment by iamoop** [comment]
By taking the `Select * from @ts` out of the From OPENJSON I got the following error from the Multiple Headers code.

Could not load file or assembly 'System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Assembly in host store has a different signature than assembly in GAC. (Exception from HRESULT: 0x80131050)

Thought I'd share that, in case it was important.

**Comment by iamoop** [comment]
A few more tests and I'm seeing this error:
Could not load file or assembly 'System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Assembly in host store has a different signature than assembly in GAC. (Exception from HRESULT: 0x80131050)

So that means I didn't load something correctly. I'll start from scratch and try again.

**Comment by geral2** [comment]
Did you fix this?

**Comment by geral2** [comment]
Depending on the version it could be fixed with the code below:
```
ALTER  ASSEMBLY [System.Runtime.Serialization] 
FROM 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Runtime.Serialization.dll' 
WITH PERMISSION_SET = UNSAFE
```

**Comment by iamoop** [comment]
Yes. I was able to fix this by reloading the dlls into GAC.
