### ISSUE TITLE
Trying to install fresh and having issues with Stored Procedure creation

### ISSUE THREAD

**Issue by iamoop** [geral2/SQL-APIConsumer#25]
I'm not sure where the issue lies here. But when trying to create the first Stored Procedure I get the following error:
Creating [dbo].[Create_HMACSHA256]...
Msg 6505, Level 16, State 2, Procedure Create_HMACSHA256, Line 1 [Batch Start Line 3]
Could not find Type 'UserDefinedFunctions' in assembly 'APIConsumer'.

I had to copy the System.Net.Http.dll from the Microsoft Framework (which is 4.0.30319) because when I tried using the one provided here it was giving me an error about the Policy.

Assembly 'System.Net.Http' could not be installed because existing policy would keep it from being used.

So this was a fresh install on a test server to try and work out what may be wrong. Thank you in advance for any help.

**Comment by iamoop** [comment]
Got this working. So closing. Still having some issues getting a token from the Auth. But that's proably user error at this point.

**Comment by cgeswein** [comment]
Hey @iamoop I'm having this exact same problem, exact same scenario. What did you do to get it working?

**Comment by cgeswein** [comment]
Never mind @iamoop  same problem as issue #10 
Didn't pay enough attention on step 5

**Comment by wtsyung** [comment]
Hi @cgeswein & @iamoop,
Greatly appreciated if you can tell me the steps to work out this problem in detail?
