### ISSUE TITLE
Method Not allowed

### ISSUE THREAD

**Issue by iamoop** [geral2/SQL-APIConsumer#26]
Finally found something I can't get past here. Not sure if it's possible to do this or not. 
The API I'm trying to connect to is here:
https://app.fasttestweb.com/FastTest/api/auth/simple

Using the APICaller_Get_Headers (because I have to pass multiple headers)
I get the following error
<!doctype html><html lang="en"><head><title>HTTP Status 405 – Method Not Allowed</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 405 – Method Not Allowed</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Method Not Allowed</p><p><b>Description</b> The method received in the request-line is known by the origin server but not supported by the target resource.</p><hr class="line" /><h3>Apache Tomcat/7.0.100</h3></body></html>

I can't supply you with the pwd or apikey through this forum. But here is basically how I have it set up:

`
--Set Header
Declare @header nvarchar(max) = '[{
								  "Name": "username",
								  "Value" :"--"
								},{
								  "Name": "pwd",
								  "Value" :"--"
								},{
									"Name": "apikey",
									"Value": "--"
								},{
									"Name": "timesent",
									"Value": "1587232384"
								},{
									"Name": "ttl",
									"Value": "1000"
									}
								
								
								
								]';

					
--Set URL
Declare @wurl varchar(max) = 'https://app.fasttestweb.com/FastTest/api/auth/simple' 

Declare @ts as table(Json_Table nvarchar(max))`

**Comment by geral2** [comment]
Hi,

Did you test it using Postman or something like that?

**Comment by geral2** [comment]
Are you sure that it's not a POST method?, Could you try with API_CallerPost_Header?

**Comment by iamoop** [comment]
No, I hadn't done that yet. But I was finally able to get a result. Yay!

Here is what I ended up with through trial and error. (Btw, I appreciate your quick reply) So you can close this. 

 DECLARE @Result AS TABLE
    (
        Token VARCHAR(MAX)
    )
    INSERT INTO @Result
    
     exec  [dbo].[APICaller_POST_headers]
    	 @URL = 'https://app.fasttestweb.com/FastTest/api/auth/simple'
    	,@headers= '{  "username": "---",
  "pwd": "---",
  "apiKey": "----",
  "timeSent": 1587233627,
  "tokenTTL": 1000 }
								'
    DECLARE @Token AS VARCHAR(MAX)

**Comment by geral2** [comment]
Could you please star the project?

**Comment by geral2** [comment]
Thank you!

**Comment by iamoop** [comment]
Done. And this is a great project. Most of my issues seem to be on my understanding of JSON. This is all new to me.
