### ISSUE TITLE
prerequest script

### ISSUE THREAD

**Issue by johncagnina** [geral2/SQL-APIConsumer#27]
Hi @geral2 ,

Is it possible to run a prerequest script. I need to get an auth header.

John

**Comment by geral2** [comment]
Hi,

Do you have any code, how we can get the headers in a prerequest?

**Comment by johncagnina** [comment]
See postman file and let me know

"info": {
		"_postman_id": "f06e8df0-1a88-4c7b-8b90-ecf353c23a6b",
		"name": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "newnotification",
			"event": [
				{
					"listen": "prerequest",
					"script": {
						"id": "1c718015-8f7c-490d-861f-abf26bb7d94d",
						"exec": [
							"function getAuthHeader(resourceUri, keyName, key) {\r",
							"\r",
							"    var d = new Date();\r",
							"    var sinceEpoch = Math.round(d.getTime() / 1000);\r",
							"    var expiry = (sinceEpoch + 3600);\r",
							"    var stringToSign = encodeURIComponent(resourceUri) + '\\n' + expiry;\r",
							"    var hash = CryptoJS.HmacSHA256(stringToSign, key);\r",
							"    var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);\r",
							"    var sasToken = 'SharedAccessSignature sr=' + encodeURIComponent(resourceUri) + '&sig=' + encodeURIComponent(hashInBase64) + '&se=' + expiry + '&skn=' + keyName;\r",
							"    console.log(sasToken);\r",
							"   \r",
							"\r",
							"    return sasToken;\r",
							"}\r",
							"postman.setEnvironmentVariable('azure-authorization',getAuthHeader(request.url,\"KeyName\", \"Key\"));\r",
							"postman.setEnvironmentVariable('current-date',new Date().toUTCString());"
						],
						"type": "text/javascript"
					}
				}
			],
			"request": {
				"method": "POST",
				"header": [
					{
						"key": "Authorization",
						"value": "{{azure-authorization}}",
						"type": "text"
					},
					{
						"key": "Content-Type",
						"value": "application/json",
						"type": "text"
					},
					{
						"key": "ServiceBusNotification-Format",
						"value": "gcm",
						"type": "text"
					},
					{
						"key": "ServiceBusNotification-Tags",
						"value": "veelead1",
						"type": "text"
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\"data\":{\"gcm.notification.body\":\"Hello the push notification \"}}"
				},
				"url": {
					"raw": "https://xdnotification.servicebus.windows.net/xdnotihub/messages/?api-version=2015-01",
					"protocol": "https",
					"host": [
						"xdnotificationpoweriq",
						"servicebus",
						"windows",
						"net"
					],
					"path": [
						"xdnotihub",
						"messages",
						""
					],
					"query": [
						{
							"key": "api-version",
							"value": "2015-01"
						},
						{
							"key": "",
							"value": null,
							"disabled": true
						}
					]
				},
				"description": ""
			},
			"response": []
		}
	],
	"protocolProfileBehavior": {}
}
