### ISSUE TITLE
GAC issue

### ISSUE THREAD

**Issue by iamoop** [geral2/SQL-APIConsumer#29]
Good evening,

So I had everything set up and running during testing. No changes to the server, but after implementing this live (same server and code I just added access to the code to be run on a routine instead of manually)

However, today when checking, I'm getting the following error when using the APICaller_Post_Headers stored procedure. (Again, this was working perfectly last week). No changes to the server that anyone knows of. 

When I run the code now, I get the following Response:

Could not load file or assembly 'System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Assembly in host store has a different signature than assembly in GAC. (Exception from HRESULT: 0x80131050)

I'm not really sure where to start in trying to figure this out.  Any help would be greatly appreciated.

**Comment by iamoop** [comment]
Just a little more information. The APICaller_Post_Headers worked. But I had created a Second one called APICaller_Post_Headers1 that allowed the @JSON as a variable. (Which was done because of another thread/conversation. 

My apologies but it's the second one that is giving the error.

Based on this

CREATE PROCEDURE [dbo].[APICaller_POST_Headers1]
	@URL [nvarchar](max),
	@Headers [nvarchar](max),
	@jSON [nvarchar](max)
WITH EXECUTE AS CALLER
AS
EXTERNAL NAME [API_Consumer].[StoredProcedures].[APICaller_POST_JsonBody_Headers]
GO

**Comment by geral2** [comment]
Good morning @iamoop,

Did you try doing this:
```

ALTER  ASSEMBLY [System.Runtime.Serialization] 
FROM 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Runtime.Serialization.dll' 
WITH PERMISSION_SET = UNSAFE
```

**Comment by iamoop** [comment]
I will as soon as I can. (VPN is currently down. So I'll let you know). Thank you for the quick reply.

**Comment by iamoop** [comment]
That worked. Thank you. Any ideas as to why that would have stopped working so that I can try to avoid it in the future?

**Comment by geral2** [comment]
Make sure the GAC was not updated.

**Comment by geral2** [comment]
Hey @iamoop , I just experienced same error in a production environment, right after installing [this](https://support.microsoft.com/en-us/help/4552931/kb4552931-cumulative-update-for-net-framework) Windows update (Cumulative Update for .Net Framework 3.5 and 4.8 Version 1903 and 1909).

There is a tools named [DQS](https://docs.microsoft.com/en-us/sql/data-quality-services/install-windows/upgrade-sqlclr-assemblies-after-net-framework-update?view=sql-server-ver15), which could be use to automatically update SQL asembly after .Net framework update.
