### ISSUE TITLE
POST Request with urlencoded data

### ISSUE THREAD

**Issue by ShobhitaSingh** [geral2/SQL-APIConsumer#30]
Hi Geraldo,

I am facing issue with Post request.

Below is my generated javascript code:

var settings = {
  "url": "https://qwerty/token",
  "method": "POST",
  "timeout": 0,
  "headers": {
    "Content-Type": "application/x-www-form-urlencoded"
  },
  "data": {
    "grant_type": "client_credentials",
    "scope": "scope.xyz",
    "client_id": "abc...",
    "client_secret": "def..."
  }
};

PostMan request for this is returning correct response.

Executing this in SP "[dbo].APICaller_POST_Headers", is throwing:

{"error":"invalid_request"}

Below is SP usage:

--Set Header
Declare @header nvarchar(max) = '[{
								  "Name": "content-type",
								  "Value" :"application/x-www-form-urlencoded"
								}]';

Declare @jsonBody nvarchar(max) = '{
								   "grant_type" : "client_credentials",
								   "scope" : "scope.xyz",
								   "client_id" : "abc...",
								   "client_secret" : "def...",
								 } '
--Set URL
Declare @wurl varchar(max) = 'https://qwerty/token'

 exec [dbo].APICaller_POST_Headers
							@wurl
							,@header 
							,@jsonBody

Please assist me in resolving this issue.

Thanks.

**Comment by geral2** [comment]
Hi @ShobhitaSingh,

This is probably due application/x-www-form-urlencoded, the SP was set with a default application/json. I will update a new version with this fix. 

Thank you.

**Comment by geral2** [comment]
Hi, 
I already fixed, I'll update the repo probably tomorrow.

**Comment by geral2** [comment]
@ShobhitaSingh  Could you try exact the same using dbo.APICaller_POST_Encoded instead?

**Comment by ShobhitaSingh** [comment]
Hi Geraldo,

I used this SP and got the error.

Declare @header nvarchar(max) = 
  '[{
		"Name": "Content-Type",
		"Value" :"application/x-www-form-urlencoded"
	},
	{
		"Name": "grant_type",
		"Value" :"client_credentials"
	},
	{
		"Name": "scope",
		"Value" :"scopeopenapi"
	},
	{
		"Name": "client_id",
		"Value" :"abc"
	},
	{
		"Name": "client_secret",
		"Value" :"def"
	}]';
--Set URL
Declare @wurl varchar(max) = 'https://qwerty/token' 
 exec [dbo].[APICaller_POST_Encoded]
							@wurl
							,@header
							,''

Error:

The 'Content-Type' header must be modified using the appropriate property or method.  Parameter name: name

Could you please assist me in correcting what I'm doing wrong here?

Thank You.

**Comment by geral2** [comment]
Hi, dbo.APICaller_POST_Enconded does not required headers. 

Could you try the script below first?

If this does not work let try with a different body Json.

```
use TEstDB
GO
DECLARE @wurl			VARCHAR(MAX)	= 'https://qwerty/token' 
	   ,@header			NVARCHAR(MAX)	= '[]' 
	   ,@grant_type		NVARCHAR(1000)	= 'client_credentials' 
	   ,@scope			NVARCHAR(MAX)	= 'scopeopenapi' 
	   ,@client_id		NVARCHAR(1000)	= 'abc' 
	   ,@client_secret  NVARCHAR(MAX)	= 'def' 
	  -- ,@audience		NVARCHAR(MAX)	= 'https://api.xxx.com' 

DECLARE @Body nvarchar(max)	= CONCAT('grant_type=',@grant_type,'&scope=',@scope,'&client_id=',@client_id,'&client_secret=',@client_secret)--,'&audience=',@audience)

DECLARE @Results AS TABLE
(
	Context varchar(max)
)

DECLARE @Result AS VARCHAR(MAX)

--INSERT INTO @Results

EXEC [dbo].[APICaller_POST_Encoded]  @URL		= @wurl
									,@Headers	= @header
									,@JsonBody		= @Body

--Result: column per value.
--SELECT 
--		 [scope]		
--		,[expires_in]	
--		,[token_type]	
--		,[access_token]
-- FROM (
--			SELECT Context 
--			  from @Results
--		)tb
--	OUTER APPLY OPENJSON  (context)  
--  WITH
--    ( [access_token]	VARCHAR(MAX)  '$.access_token'
--	, [scope]			VARCHAR(1000) '$.scope'
--	, [expires_in]		VARCHAR(100)  '$.expires_in'
--	, [token_type]		VARCHAR(100)  '$.token_type'
--    );

	----Result: Row per value 

 --SELECT  B.*
 -- FROM (
	--		SELECT Context 
	--		  from @Results
	--	)tb
	--OUTER APPLY OPENJSON  (context) B
```

**Comment by ShobhitaSingh** [comment]
Hi Geraldo,

Provided sample works.

Thanks for all your help.

Thank You !!

**Comment by geral2** [comment]
Could you please star the project?
