### ISSUE TITLE
APICaller_GET_Headers_EXT

### ISSUE THREAD

**Issue by pmaldonato** [geral2/SQL-APIConsumer#32]
Gerald,
I've pulled the master and there's no Created Procedure for APICaller_GetHeader_EXT. The only mention on it in the README is  Line 389 where it's being executed in ### **Sample calling multiples headers Get Method**  " @i = [dbo].[APICaller_GET_Headers_EXT]". I'm new to this. Is it in another branch?

**Comment by geral2** [comment]
Hi @pmaldonato,

You're right. The correct procedure name is dbo.APICaller_GET_Extended.

You can find the script [here](https://github.com/geral2/SQL-APIConsumer/releases/download/v2.2/Updated.v2.2.sql)

```
GO
CREATE PROCEDURE [dbo].[APICaller_GET_Extended]
@URL NVARCHAR (MAX) NULL, @JsonBody NVARCHAR (MAX) NULL, @Headers NVARCHAR (MAX) NULL
AS EXTERNAL NAME [API_Consumer].[StoredProcedures].[APICaller_GET_Extended]

```

Thank you, I just updated the documentation. Let me know if it works.

**Comment by pmaldonato** [comment]
Yes, that did it. Thanks.
