### ISSUE TITLE
API_Caller_POST_Headers example

### ISSUE THREAD

**Issue by sramsay335i** [geral2/SQL-APIConsumer#33]
Hi I have successfully used the APICaller_GET_Headers call in SQL as in:
DECLARE @apikey as varchar(max) = 'xxxxxxxxx'
DECLARE @json AS TABLE (result NVARCHAR(MAX))
DECLARE @URL AS VARCHAR(MAX) = 'https://xxx/xxx/api/xxx'
DECLARE @header NVARCHAR(MAX) = '[{"Name": "X-API-Token","Value" :"' + @apikey + '"}]'
INSERT INTO @json(result) EXEC WTL.dbo.APICaller_GET_Headers @URL, @header
SELECT result FROM @json
   However, I cannot get this to work with API_POST_Headers call.   Do you have a working example?  
The following curl command works:
curl -g -k -X POST https://xxx/xxx/api/xxx --header "X-Api-Token: xxxx"
Thanks,
Sean

**Comment by geral2** [comment]
Hi @sramsay335i,

**Take a look to the issue [21](https://github.com/geral2/SQL-APIConsumer/issues/21)**

Did you try something like this;
```

EXEC [dbo].[APICaller_POST_Headers]
	@URL = 'https://xxx/xxx/api/xxx'
       , @Headers =  '[{
				"Name": "X-API-TOken",
				"Value" :"xxxx"
				}]' 
        , @jSON = '{body}'
		--, @jSON = '' -- if not require to send any data
```

Let me know if it works.

**Comment by sramsay335i** [comment]
Hi Geraldo,
  Thank you very much for replying so quickly.   I tried out your code but
the problem is the stored procedure only requires two parameters (URL and
Header).  I can't use the JSON parameter.
   I created the APICaller_POST_Headers stored procedure from the
documentation in the following link:
https://github.com/geral2/SQL-APIConsumer
   Should I modify the procedure to allow for the JSON parameter?  or will
that not work?
Thanks,
Sean

**Comment by geral2** [comment]
You're right @sramsay335i,

I just updated the documentation. There is missing the creation script for APICaller_POST_JsonBody_Header.

```
CREATE PROCEDURE [dbo].[APICaller_POST_JsonBody_Header]
	@URL NVARCHAR (MAX)  
  , @Headers NVARCHAR (MAX)  
  , @jSON NVARCHAR (MAX)  
AS EXTERNAL NAME [API_Consumer].[StoredProcedures].APICaller_POST_JsonBody_Headers
```

```
EXEC [dbo].APICaller_POST_JsonBody_Header
	@URL = 'https://xxx/xxx/api/xxx'
       , @Headers =  '[{
				"Name": "X-API-TOken",
				"Value" :"xxxx"
				}]' 
        , @jSON = '{body}'
```

Please give a try.

**Comment by sramsay335i** [comment]
Hi Geraldo,
That works perfectly!
Many thanks,
Sean

**Comment by geral2** [comment]
You're welcome!, Thank you for starring the project.
