### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by valentinb1** [geral2/SQL-APIConsumer#35]
Hello Geraldo,
I've been using SQL-APIConsumer for several months on https://www.commandgps.com/ibis/rest/api/v2/ and it works great!
Now, I am trying to use it on a different API, but no luck.
The API in question is:
https://plgsearchapi.tmwcloud.com/s
Swagger: https://plgsearchapi.tmwcloud.com/s/swagger.json
Any GET request to it returns: "The request was aborted: Could not create SSL/TLS secure channel" or "The underlying connection was closed: An unexpected error occurred on a send."
Even the simplest one: EXEC  [dbo].[APICaller_GET] 'https://plgsearchapi.tmwcloud.com/s/version'
I tested this API using Postman and all works as expected.
I don't know what to do next. Please help.
Thank you,
Valentin

**Comment by geral2** [comment]
Hello @valentinb1, thank for Starring the project.

Did you try with the latest version?... I just tested those API, It worked as expected.

![image](https://user-images.githubusercontent.com/5836150/87736243-a5001a00-c7a5-11ea-8136-99827225923a.png)


Confirm which version of the API are you working with:

![image](https://user-images.githubusercontent.com/5836150/87736194-8c8fff80-c7a5-11ea-8c4b-6a320bbbb89e.png)

**Comment by valentinb1** [comment]
Hi Geraldo,
You are correct: I had an older version of API_Consumer.
I upgraded it to current and now all works.
Thank you!
Valentin

**Comment by pmaldonato** [comment]
I was using a swagger API and could use  [APICaller_GET] once I got authorized, I ended up using  [APICaller_GET_Extended] to get around it. Thanks, I'll pull and simplify my code.
