### ISSUE TITLE
Patch Method

### ISSUE THREAD

**Issue by rediajme** [geral2/SQL-APIConsumer#36]
Hello geral2

Is it possible to add a Patch Method to make partial updates? I am trying to compile your source in VS 2015, but it does not compile and I have not managed to discover what I am doing wrong, I am not sure if it is framework or Newtonsoft version

I'd appreciate it if you could give me a hint to build

**Comment by geral2** [comment]
Hello @rediajme,

That's a good one, I'll try to update it adding to new methods, one Patch and another generic that make you able to send which method (POST,PATCH,GET).

Could you please share what error it's throwing when building?

**Comment by rediajme** [comment]
Thanks for your prompt response, at the time of compiling I see that the solution is with Framework 4 and it generates the following list of error messages I think it is for compatibility with the framewor but I'm not sure about it
![nameof](https://user-images.githubusercontent.com/24400164/89569630-9f1cb800-d7ea-11ea-8b70-624750b532ac.png)
![Nullable](https://user-images.githubusercontent.com/24400164/89569632-9fb54e80-d7ea-11ea-8cc8-5a5a3c27da0c.png)

**Comment by geral2** [comment]
Can you confirm if it's using 4.0 as Target Framework?

**Comment by rediajme** [comment]
Yes of course
![framework](https://user-images.githubusercontent.com/24400164/89575971-2ae71200-d7f4-11ea-9314-5d2cd1123d7c.png)

**Comment by geral2** [comment]
Confirm the compiler version and what .net framework are you working on.

![image](https://user-images.githubusercontent.com/5836150/89586192-3eeb3d80-d80d-11ea-8570-2e01a1123e54.png)

**Comment by rediajme** [comment]
Framework
![frameworkW](https://user-images.githubusercontent.com/24400164/89593235-3a765300-d814-11ea-9b1d-990865268fc2.png)

**Comment by rediajme** [comment]
Después de mucho validar veo que debe compilar con C# 6, sin embargo, después de verificar versiones de NewtonSoft.Json y System.Net.Http al compilar VS indica que la referencia a NewtonSoft esta perdida
![Framework](https://user-images.githubusercontent.com/24400164/89834728-03ac7f80-db29-11ea-91bd-19042eddcb60.png)

**Comment by geral2** [comment]
Saludos,

Intentaste borrando la referencia e instanciandola nuevamente?. Usa una version especifica, creo que la 11.0. La dll esta en el folder con el mismo nombre. Me dejas saber. Aun no he tenido tiempo de hacer el cambio del Patch.
