### ISSUE TITLE
New Issue with Post

### ISSUE THREAD

**Issue by iamoop** [geral2/SQL-APIConsumer#40]
So. First. Thank you for this program. I've been using it for awhile now with mostly GET's ad it's working wonderfully. 
But I have a new POST project and I've run into an error. I'm not sure if it's something you can solve or not. Or if it's something that I've screwed up with. 

Anyway. I'm using the APICaller_Post (no auth needed as it using an access Key that I'm putting in the URL directly. 
After formatting the JsonBody for the API array I get the following error. 
{"success":false,"error":{"code":0,"type":"prohibited_api_client_id"}}

That prohibitied api client id is what I'm wondering about. Is it because it's coming from SQL or something else?  Any thoughts would be helpful. 

I'm attempting to use the Use Template API for Eversign
https://eversign.com/api/documentation/methods#get-document-template
Any thoughts would be appreciated. Thank you in advance

**Comment by geral2** [comment]
You're welcome @iamoop,

Could you please confirm what procedure are you using, since you are getting a response means CLR Procedure comunicated successfully with the API, I do not see that response as part of the errors in [errors](https://eversign.com/api/documentation/methods#errors).

I did try the code below;

`Declare @header nvarchar(max) = 
  '[{
		"Name": "Content-Type",
		"Value" :"application/json; charset=utf-8"
	}]';
--Set URL
Declare @wurl varchar(max) = 'https://api.eversign.com/api/document?access_key=d5aee16f39336a9ce5398ff2fe64d9fb&business_id=239114' 
		,@JSONbody NVARCHAR(MAX) = '{
	"sandbox": 0,
	"is_template": 1,
	"is_draft": 0,
	"title": "test_title",
	"message": "test_message",
	"use_signer_order": 0,
	"reminders": 0,
	"require_all_signers": 0,
	"files": [{
		"name": "My Template File",
		"file_url": "https://website.com/contract.pdf",
		"file_id": "",
		"file_base64": ""
	}, {
		"name": "My Second Template File",
		"file_url": "https://website.com/second_contract.pdf",
		"file_id": "",
		"file_base64": ""
	}],
	"signers": [{
		"id": 1,
		"role": "Client",
		"name": "",
		"email": "",
		"required": 1
	}],
	"recipients": [],
	"meta": {
		"some_key": "some_value",
		"another_key": "another_value"
	},
	"fields": [
		[{
			"type": "signature",
			"x": "120.43811219946572",
			"y": "479.02760463045416",
			"width": "120",
			"height": "35",
			"page": "2",
			"signer": "1",
			"name": "",
			"identifier": "unique_field_identifier_1",
			"required": 1,
			"merge": 0,
			"readonly": 0,
			"validation_type": "",
			"text_size": "",
			"text_color": "",
			"text_font": "",
			"text_style": "",
			"value": "",
			"options": [],
			"group": ""
		}]
	]
}'
Declare @ts as table
(
	Json_Result nvarchar(max),
	ContentType varchar(100),
	ServerName varchar(100),
	Statuscode varchar(100),
	Descripcion varchar(100),
	Json_Headers nvarchar(max)
)
declare @i as int 
 
 --insert into @ts
 --Get Account Data
 exec @i = [dbo].[APICaller_POST_Extended]
							@wurl
							,@header
							,@JSONbody`

I got the response below because my free account.
![image](https://user-images.githubusercontent.com/5836150/100489375-3d11f680-30ea-11eb-874e-75a70595b012.png)

**Comment by iamoop** [comment]
I was using API_Caller_Post. I don't have Post_Extended. So that's probably it. I seem to have an older version. I'll get it updated and if I still have a problem I'll let you know. Sorry I missed it, but as always you are awesome for responding so fast.

**Comment by iamoop** [comment]
And I'm just going to say this again. Because I think it needs to be said. This code is amazing, and the fact that you keep updating it as needed is a bonus. It has literally saved me a hundred or more hours in helping my clients extend their functionality.

**Comment by iamoop** [comment]
I had a few other things to work out on the formatting. But this API_Caller_Post_Extended did the trick. 

Again, thank you for helping. Thank you for this program and thank you for the quick reply. It is much appreciated.

**Comment by geral2** [comment]
I'm glad to heard that It works, I'ts my preasure to keep working on it. Anything else that you need just let me know.
I had another update that I haven't updload yet regarding #36 which would allow call another HTTP methods as PATCH, PUT.

I really appreciate your donation, thank you!.

**Comment by iamoop** [comment]
My pleasure. I, honestly, never saw the option to donate/sponsor before today or I would have done it ages ago. This code is a blessing.

**Comment by geral2** [comment]
It was added in the last update. Can we close this issue?

**Comment by iamoop** [comment]
Absolutely. 


 
 
  On Fri, Nov 27, 2020 at 9:05 PM, Geraldo Diaz<notifications@github.com> wrote:   


It was added in the last update. Can we close this issue?

**Comment by geral2** [comment]
Thank you!
