### ISSUE TITLE
Oauth 2 with APICaller_POST_Encoded

### ISSUE THREAD

**Issue by sramsay335i** [geral2/SQL-APIConsumer#42]
Hi Geral,

   When I use the your SQL example, I get the following json string back:{"access_token":"5f36e31256c2db5ec3d68f6b5206aafa23c6ab6f","expires_in":3600,"token_type":"Bearer","scope":"api"}
   I was expecting to get back the json result of the API I was calling in the @audience variable.   Here's the SQL example I am using:

DECLARE @wurl VARCHAR(MAX)	= 'https://westshorelms.docebosaas.com/oauth2/token' 
DECLARE @header VARCHAR(MAX)	= '[]' 
DECLARE @grant_type VARCHAR(20)	= 'client_credentials' 
DECLARE @client_id VARCHAR(15)	= 'xxx' 
DECLARE @client_secret VARCHAR(40)	= 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' 
DECLARE @audience VARCHAR(100)	= 'https://westshorelms.docebosaas.com/manage/v1/user' 
DECLARE @Body VARCHAR(MAX)	= CONCAT('grant_type=',@grant_type,'&client_id=',@client_id,'&client_secret=',@client_secret,'&audience=',@audience)
DECLARE @Results AS TABLE (Context VARCHAR(MAX) NOT NULL)
INSERT INTO @Results EXEC dbo.APICaller_POST_Encoded @URL = @wurl, @Headers = @header, @JsonBody = @Body
SELECT Context FROM @Results 

   Do you see anything odd with the SQL?   The bearer token I get back in the string doesn't work when I try calling the @audience URL in Postman using Bearer Token Authorization.

Sean

**Comment by geral2** [comment]
Hi @sramsay335i,
Could you please add the code below after your select context from @result;

Let me know if it works. Keep in mind you need to create the procedure dbo.APICaller_GETAuth.

```

--Result: column per value.
DROP TABLE IF EXISTS #TokenData;

SELECT 
		 [scope]		
		,[expires_in]	
		,[token_type]	
		,[access_token]
INTO #TokenData
 FROM (
			SELECT Context 
			  from @Results
		)tb
	OUTER APPLY OPENJSON  (context)  
  WITH
    ( [access_token]	VARCHAR(MAX)  '$.access_token'
	, [scope]			VARCHAR(1000) '$.scope'
	, [expires_in]		VARCHAR(100)  '$.expires_in'
	, [token_type]		VARCHAR(100)  '$.token_type'
    );

	----Result: Row per value 

DECLARE @Token	   AS VARCHAR(MAX)	

SELECT @Token   = CONCAT(token_type,' ',access_token)
 FROM #TokenData 

DELETE FROM @Results;

INSERT INTO @Results
EXEC  [dbo].[APICaller_GETAuth]
 @URL		=  @audience
,@Token		= @Token

SELECT Context 	from @Results
```

**Comment by geral2** [comment]
Hey, @sramsay335i  Did it work?
