### ISSUE TITLE
ERROR: Procedure APICaller_POST_Extended - Column name or number of supplied values does not match table definition.

### ISSUE THREAD

**Issue by hajrah** [geral2/SQL-APIConsumer#44]
Hi, 

I am facing this issue while using APICaller_POST_Extended and can't seem to resolve it. The details passed are correct as APICaller_POST_JsonBody_Header works perfectly. I am assuming there is an issue while receiving data into the table @JResp. The code for that is the same from your example. It can be something silly too that my eyes haven't caught. Hope you can help. 

---------------------------------------------------------------------------------------------------------------------------------------------
ERROR DESCRIPTION: (Screenshot attached)
A .NET Framework error occurred during execution of user defined routine or aggregate 'APICaller_POST_Extended': 
System.Data.SqlClient.SqlException: Column name or number of supplied values does not match table definition.
System.Data.SqlClient.SqlException: 
   at Microsoft.SqlServer.Server.SmiEventSink_Default.DispatchMessages(Boolean ignoreNonFatalMessages)
   at Microsoft.SqlServer.Server.SqlPipe.SendResultsStart(SqlDataRecord record)
   at SQLAPI_Consumer.Helper.SendResultValue(String ColumnName, String Value)
   at StoredProcedures.APICaller_POST_Extended(SqlString URL, SqlString Headers, SqlString JsonBody)
. User transaction, if any, will be rolled back.
---------------------------------------------------------------------------------------------------------------------------------------------
CODE without ERROR:

Declare @JResp as table (Json_Result nvarchar(max))

insert into @JResp
EXEC [APICaller_POST_JsonBody_Header] @URL, @Header, @Body
	
SELECT * from @JResp

select @Result = Json_Result from @JResp

---------------------------------------------------------------------------------------------------------------------------------------------
CODE with ERROR:

Declare @JResp as table (
	Json_Result nvarchar(max),
       ContentType varchar(100),
	ServerName varchar(100),
	Statuscode varchar(100),
	Descripcion varchar(100),
	Json_Headers nvarchar(max)
)

declare @i as int 

insert into @JResp
EXEC @i = [APICaller_POST_Extended] @URL, @Header, @Body

select @Result = Json_Result, @Statuscode = Statuscode, @Descripcion = Descripcion from @JResp

![APICaller_POST_Extended](https://user-images.githubusercontent.com/11899601/108081392-59d71e00-708a-11eb-8825-962391bf1b80.JPG)

**Comment by geral2** [comment]
Hi @hajrah,

Could you comment out this line --insert into @jresp?. Just to confirm if it's returning what it should.

--insert into @jresp
EXEC @i = [APICaller_POST_Extended] @url, @Header, @Body

**Comment by hajrah** [comment]
Hi @geral2 

After commenting it gives an error stating "Object reference not set to an instance of an object." 

Screenshot attached

![APICaller_POST_Extended_NoInsert](https://user-images.githubusercontent.com/11899601/108090001-9b1ffb80-7093-11eb-9847-c12f182f84a7.JPG)
