### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by patbc77** [geral2/SQL-APIConsumer#48]
Buenas 
He descargado el código y quería ver la funcionalidad como estaba desarrollada. Tengo visual studio 2015. 
Version 4.8 y sql Server 2014. 
Me da un error al intentar abrirlo y deduzco que no es compatible ¿correcto?

**Comment by geral2** [comment]
Saludos,

Deberia funcionar sin problemas en cualquier version igual o mayor a SQL Server 2012. 

Actualmente lo trabajo en 
![image](https://user-images.githubusercontent.com/5836150/131508986-51e72299-98f0-413e-ac0a-34379a64803a.png)

Pero deberia abrir en Visual Studio 2015+.

**Comment by geral2** [comment]
Saludos,

Esto respondio tu pregunta?

**Comment by patbc77** [comment]
Bueno yo no he conseguido abrir el código. Supongo que será por algo en la configuración del entorno.

**Comment by geral2** [comment]
Puedes postear el error que te da?
