### ISSUE TITLE
upgrade instructions

### ISSUE THREAD

**Issue by ghost** [geral2/SQL-APIConsumer#49]
I believe I am running version 2.2 but would like to upgrade to 2.3.5.  What is the recommended upgrade path?  Can I just replace the dll or do I need to start all over?  Any tips would be appreciated.

**Comment by geral2** [comment]
Hi @bradrg ,

Did you figure it out?

Sorry for the late response. I think the best way to do it. It's remove all the dependecies for API_COnsumer Assembly from DB.
Then remove that assembly and re-create everything.

There is a way in which we could basically alter the assembly with the latest version but it uses to fail if if there is any new parameter or renamed object.

Any issue let me know.
