### ISSUE TITLE
Using POST to upload a SQL table

### ISSUE THREAD

**Issue by sramsay335i** [geral2/SQL-APIConsumer#50]
Is it possible to do this curl command with APICaller_POST_Headers?   The HMI_DATA_20211019_1135 is the data table.

curl --location --request POST “https://xxx.xxx.xxx" --header “Content-Type: application/json” --data-raw “{ 
    \“data\“: [ 
        \“HMI_DATA_20211019_1135\”
    ] 
}”

**Comment by geral2** [comment]
Hi @sramsay335i,

Yes, but you will need to translate this curl request to a procedure parameters expected by this SP.

For instance;

![image](https://user-images.githubusercontent.com/5836150/147615580-67060c62-4f99-43d5-bfbb-c7f0d1675c3c.png)


![image](https://user-images.githubusercontent.com/5836150/147615599-061c7247-44a2-4b09-a5d3-dbfabd3aa57b.png)
