### ISSUE TITLE
Unterminated string. 

### ISSUE THREAD

**Issue by rediajme** [geral2/SQL-APIConsumer#51]
Hi geral2

I have a problem when I use **APICaller_POST Extended**, I am sending the following json:

`{
    "eventName": "nps_tiendas_fisicas",
    "items": [
        {
            "email": "xxxxxxxxx@gmail.com",
            "attributes": {
                "CLIENTE": "742707",
                "NOMBRE": "xxxxxx xxxxxxx xxxxx",
                "FACTURA": "0002-00929",
                "NAME": "xxxxx xxxxxx CARRERA 7",
                "FECHA": "2022-02-04T00:00:00",
                "link": "https://co.totto.com/info/encuesta-satisfaccion-nps?tipodesatisfaccion=NPS&email=xxxxxxxxxx@gmail.com&canal_origen=TIENDA&nombre=xxxxx%20xxxx%20xxxx&Id_Factura=0002-00929&NombreTienda=xxxx%20xxxxxx%20xxxx%207"
            }
        }
    ]
}`

but i get the following error
Unterminated string. Expected delimiter: ". Path '[1].Value', line 9, position 6.

I did tests from postman and the structure is correct, consulting on the internet I found that the result is most likely to be sent in batches,

**Comment by geral2** [comment]
Hi @rediajme,

Could you please specify how are you sending the parameters in this procedure execution?

**Comment by rediajme** [comment]
of course

thanks for your time


This procedure has 3 parameters (EXEC [dbo].[APICaller_POST_Extended] @wurl,@Header,@JSONbody)

the first two I am defining in this way : 
`SET @header  = '[{
						"Name": "authorization",
						"Value" :"BaZTQzMzlhNjhGFhZjFiNjk3NDE"
					},
					{
						"Name": "Content-Type",
						"Value":"application/json
					}								
					]';
	SET @wurl = 'https://track.XXX.com/contacts/event/bulk'`

and @jsonbody I take a query to a table and convert it to json format

`DECLARE database_cursor CURSOR FOR
		
			SELECT FACTURA,CLIENTE,CORREO FROM #temp1

		OPEN database_cursor
		FETCH NEXT FROM database_cursor
		INTO @FACTURA,@CLIENTE,@CORREO
		WHILE @@FETCH_STATUS = 0
			BEGIN
				INSERT INTO @json
				SELECT @CORREO email,
				(SELECT CLIENTE,NOMBRE,FACTURA,NAME,FECHA,link FROM #temp2 
				WHERE FACTURA = @FACTURA and CLIENTE = @CLIENTE
				FOR JSON PATH,INCLUDE_NULL_VALUES) attributes 

			FETCH NEXT FROM database_cursor
			INTO @FACTURA,@CLIENTE,@CORREO
			END
		CLOSE database_cursor;
		DEALLOCATE database_cursor;

		SET @jsoni = (SELECT 'nps_tiendas_fisicas' eventName,(SELECT * FROM @json FOR JSON AUTO) items
		FOR JSON PATH)

		SELECT @JSONbody = ltrim(rtrim(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(@jsoni,'"[',''),']"','' ),'\',''),'}}]}]','}}]}'),'[{"eventName"','{"eventName"')))
		SELECT @JSONbody
		
		

		EXEC [dbo].[APICaller_POST_Extended] @wurl,@Header,@JSONbody`


this code generates the json structure with 50 records

`{
    "eventName": "nps_tiendas_fisicas",
    "items": [
        {
            "email": "",
            "attributes": {
                "CLIENTE": "",
                "NOMBRE": "",
                "FACTURA": "",
                "NAME": "",
                "FECHA": "",
                "link": ""
            }
        },
        {
            "email": "",
            "attributes": {
                "CLIENTE": "",
                "NOMBRE": "",
                "FACTURA": "",
                "NAME": "",
                "FECHA": "",
                "link": ""
            }
        }
   ]
}`

to validate the generated structure, I copy it and send it from Postman

**Comment by geral2** [comment]
There is a missing " in teh header definition... in application/json. I think that may be the problem. :D

SET @header = '[{ "Name": "authorization", "Value" :"BaZTQzMzlhNjhGFhZjFiNjk3NDE" }, { "Name": "Content-Type", "Value":"application/json } ]'; SET @wurl = 'https://track.XXX.com/contacts/event/bulk'

**Comment by geral2** [comment]
Did it work? @rediajme
