### ISSUE TITLE
Upgrade to .NET 4.8 breaks API_Caller

### ISSUE THREAD

**Issue by sramsay335i** [geral2/SQL-APIConsumer#53]
Hi,
  We recently upgraded our database server with .NET 4.8 Framework in which our API_Caller dlls reside on.   This broke our API_Caller assemblies.  

  The first error reported was the System.Runtime.Serialization.dll wasn't loaded.  I ran the following SQL from your site:
ALTER  ASSEMBLY [System.Runtime.Serialization] 
FROM 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Runtime.Serialization.dll' 
WITH PERMISSION_SET = UNSAFE

  Then I get the following error:
An error occurred in the Microsoft .NET Framework while trying to load assembly id 65549. The server may be running out of resources, or the assembly may not be trusted with PERMISSION_SET = EXTERNAL_ACCESS or UNSAFE. Run the query again, or check documentation to see how to solve the assembly trust issues. For more information about this error: 
System.IO.FileLoadException: Could not load file or assembly 'api_consumer, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An error relating to security occurred. (Exception from HRESULT: 0x8013150A)
System.IO.FileLoadException: 

  I tried the following SQL:
ALTER  ASSEMBLY [API_Consumer] 
FROM 'C:\APIConsumer_DLL\API_Consumer.dll' 
WITH PERMISSION_SET = UNSAFE

  And this is the error I get:
ALTER ASSEMBLY failed because the source assembly is, according to MVID, identical to an assembly that is already registered under the name "API_Consumer".

 Any ideas on how we can fix this?
Thank you,
Sean

**Comment by sramsay335i** [comment]
Hi Geral,
  I uninstalled everything and re-installed all the assemblies/functions/stored procedures with success.   I probably should have done that before I posted this issue. 
   Thanks and another thanks for a great piece of code, we use this multiple times a day.
Cheers,
Sean

**Comment by geral2** [comment]
Hi @sramsay335i,

I just saw it. Great to heard that it worked after reinstalling. I'll be updating a new version of this project soon. Where I did implement a table value function to calls the API for GET request. Avoiding to create temporary tables.

Appreciate the feedback.
