### ISSUE TITLE
Installation on Windows Server 2016 / SQL 2012 SP4 Fails

### ISSUE THREAD

**Issue by lawrenceong001** [geral2/SQL-APIConsumer#7]
when i try to create the assembly api_consumer, I'm faced with the error message: 
Msg 6586
Assembly 'System.Net.Http' could not be installed because existing policy would keep it from being used.

**Comment by lawrenceong001** [comment]
it looks like if I installed it from the framework folder (v4.0.30319) it works. however, it appears that this is an older version (4.0.0.0) whereas the one bundled is 4.0.1.0.

**Comment by lawrenceong001** [comment]
hi, 
the framework is v4.0.30319. this was a base install of windows 2016. the file version is 4.7.2661.0. 

I'm also getting some other specific issues:
1. SQL 2012 does not allow default parameters for CLR (Default parameter values for CLR types, nvarchar(max), varbinary(max), and xml are not supported.)
2. OPENJSON is not available for SQL 2012.

tks
lawrence

**Comment by lawrenceong001** [comment]
I remove the default parameters, and avoided the use of OPENJSON (used the function mentioned here: https://www.red-gate.com/simple-talk/sql/t-sql-programming/consuming-json-strings-in-sql-server/). it seems to be working now. I noticed, though, the first call took a substantial amount of time to execute. 

tks
Lawrence

**Comment by geral2** [comment]
You are right, this was developed for SQL Server 2016. And as you realized OPENJSON is optional. I will update the readme file with this that you found. I really appreciate your feedback since this will help other people that facing same error..

**Comment by lawrenceong001** [comment]
hi -- yes this is now resolved. sorry for the late note as I'd been working on another issue.
