### ISSUE TITLE
apicaller_get returns only 3998 characters of the web api...

### ISSUE THREAD

**Issue by lawrenceong001** [geral2/SQL-APIConsumer#8]
hi again,

it looks like, at least from my end, that i'm only getting 3998 characters back from the query. I've tried using SSMS, SQLCMD, as well as OSQL, but they don't seem to give me back the entire object. have you tried this and if so how do you test if the entire object or string is returned?

tks
Lawrence

**Comment by geral2** [comment]
@lawrenceong001  Could you give a try?

**Comment by lawrenceong001** [comment]
let me grab the latest and give it a whirl -- tks
