### ISSUE TITLE
Unable to install key.pfx due

### ISSUE THREAD

**Issue by AndyStobirski** [geral2/SQL-APIConsumer#9]
~~Apparently, I'm missing a password~~

~~A straightforward compile produces the following message:~~

~~Error 03325: Cannot import the following key file: Key.pfx. The key file may be password protected. To correct this, try to import the certificate again or manually install the certificate to the Strong Name~~

~~Attempting to use the following:~~

~~C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools>sn -i E:\SQL-APIConsumer\API_Consumer\Key.pfx VS_KEY_E6613A61F562B5E3~~

~~prompts me for a password.~~

~~A little help?~~

Just remembered I can unsign the assembly. Nevermind.

**Comment by geral2** [comment]
Any another issue just let me know.
